
[project]
name = "ilmli-uzbek-bot"
version = "0.1.0"
description = "Telegram bot for Ilmli Uzbek charity project"
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram",
    "python-dotenv",
    "Pillow"
]
